add_newline = false

# Clean layout with monochrome connectors
format = """
$cmd_duration \
$directory \
[󰜥](dim white) \
$git_branch\
$git_status
$character"""

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:white fg:black"
truncation_length = 3
# White Pill with Black text
format = '[](white)[󰉋 $path]($style)[](white)'

[git_branch]
symbol = "󰘬"
style = "bg:white fg:black"
# Matching White Pill
format = '[](white)[$symbol $branch]($style)[](white)'

[git_status]
style = "bg:cyan fg:black" 
# Using Cyan as the "accent" filler color for status alerts
format = '[ ](cyan)[$all_status]($style)[](cyan)'

[cmd_duration]
min_time = 0
style = "bg:white fg:black"
format = '[](white)[󰪢 $duration]($style)[](white)'

[character]
# Simple Blue/Red for the actual prompt characters
success_symbol = "[   ](bold blue)"
error_symbol = "[   ](bold red)"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"GitHub" = " 󰊤 "
